axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
  amqp:
    exchange: events
  eventhandling:
    processors:
      name:
        source: eventsQueueMessageSource
server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: auction-query-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:admin123@localhost:27017/authdb?authSource=admin}   
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eauction:
  rabbitmq:
    queue: events

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG